### ISSUE TITLE
Do we need acetate.copy(pattern) for static assets?

### ISSUE THREAD

**Issue by patrickarlt** [patrickarlt/acetate#18]
Possible extension?

**Comment by patrickarlt** [comment]
@paulcpederson You are the one who originally wanted this. If you don't want this any more can you say so and I can close this?

**Comment by paulcpederson** [comment]
Go ahead and close it. I think this is something people can clearly manage by themselves

**Comment by paulcpederson** [comment]
Definitely not necessary for 1.0 in my mind.
