### ISSUE TITLE
Acetate CLI part of Acetate?

### ISSUE THREAD

**Issue by paulcpederson** [patrickarlt/acetate#29]
Right now, if a project uses acetate, you need to install both `acetate` and `acetate-cli`.

Furthermore, most of acetate-cli is just trying to figure out where acetate is. The real business logic of the CLI is in [lib/cli.js](https://github.com/patrickarlt/acetate/blob/master/lib/cli.js). So why not just put acetate-cli in the `bin/` folder and when people `npm install acetate --save-dev` they get a working copy of the acetate-cli so they can just add scripts for building. like:

```
"scripts": {
  "build": "acetate build",
  "serve": "acetate serve"
}
```

I know that middleman, metalsmith, and most other static site generators operate like this.

---

I'm sure you thought about this, so what were your reasons for breaking acetate-cli out of the main project?

**Comment by paulcpederson** [comment]
If you decide to do this, I'm more than willing to open a pr with this work.

**Comment by paulcpederson** [comment]
To leave a paper trail on this, the basic reasoning behind having a separate cli is that users can globally install the cli, while keeping acetate proper at whatever version their project is using. (This is what grunt does).

If the cli was a part of acetate, and you globally installed it, the cli would always use the global acetate and not whatever version of acetate that was in your project.

[Gulp](http://gulpjs.com/) gets around this because they make you require your local gulp in the `Gulpfile.js`. So it is the same module, but because all the cli does is load a file that requires gulp from the project directory, the gulp you are using is actually the one you installed in your project.

---

ways around this:

1. Keep the modules separate. Just deal with people needing to `npm install -g acetate-cli`
2. Move it to acetate proper, but figure out a magical way to use the right acetate (tried this, it was hacky and weird)
3. Don't install it globally at all and have people run commands in npm scripts or [add `./node_modules/.bin` to their $PATH](https://twitter.com/brianloveswords/status/501014961058222080)
4. Require acetate from the `acetate.conf.js` file and use the acetate that is required by that file (the Gulp approach)

**Comment by patrickarlt** [comment]
> Keep the modules separate. Just deal with people needing to npm install -g acetate-cli

I feel like this is still the best option given how acetate evolved as a project. Doing this like Gulp (global install requiring local `gulp`) would probably be to hard to pull off at this point.
