### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by paulcpederson** [patrickarlt/acetate#30]
Best practice to have a `CHANGELOG.md`, preferably using [standard formatting](http://keepachangelog.com/)

**Comment by patrickarlt** [comment]
@paulcpederson I will probably want to advance everything to `0.1.0` by the end of this week this would probably be a good time to start keeping a changelog and automating the release process. Is this something you and @ngoldman could setup? Maybe on Friday?

**Comment by ngoldman** [comment]
@paulcpederson thought you meant http://github.com/feross/standard for a second. That would be cool too. There's also https://github.com/Flet/semistandard if you're more comfortable with that @patrickarlt. I endorse both (I'm a minor contributor to both also :grin:). I think `standard` is more widely adopted and aggressively maintained (@Flet is a maintainer on both) but both have already gotten wide adoption.

**Comment by paulcpederson** [comment]
@patrickarlt yeah. I can certainly put the together for you

**Comment by paulcpederson** [comment]
addressed in #44
