### ISSUE TITLE
Shift to event based API for the Acetate object

### ISSUE THREAD

**Issue by patrickarlt** [patrickarlt/acetate#41]
Right now the `acetate(options, callback)` method looks a little weird.

```js
var site = acetate(options, function(error, site){
  // this gets called every build...
});
```

This makes managing stuff just a little harder in places like the grunt plugin https://github.com/patrickarlt/grunt-acetate/blob/master/tasks/acetate.js#L49-L66 where you need to do things to `site` after the build finishes but site is both inside and outside the function context. This also breaks the expectation that callbacks will only run once.

This could be WAY cleaner with the events API.

```js
var site = acetate(options);

site.on('build', function(e){
  // do something whenever the site builds, could contain a summary of the build, any errors or warnings, ect...
});

site.once('build', function(e){
  // do something the next time the site builds, could contain a summary of the build, any errors or warnings, ect...
});
```

with `0.0.27` the acetate object is only emitting `build` and `log` events, but for testing we could emit pretty much anything at any point. This would make writing test easier, writing tools easier and overall cleanup the API.

**Comment by patrickarlt** [comment]
This would be the last breaking API change before `0.1.0`.

**Comment by ngoldman** [comment]
@patrickarlt I would encourage using the event emitter pattern and coming up with a relatively settled list of events related to all the major things one might want to subscribe to. Very simple implementation example:

* https://github.com/ngoldman/module-init/blob/master/index.js#L27-L33
* doc: https://github.com/ngoldman/module-init#node-api

In the above I'm mixing callbacks and events. Not sure how I feel about doing that. Probably better to stick to one or the other.

Note that events might fire before you register an event listener if you start the thing immediately on instantiation. That may not be an issue depending on how it's designed. For my purposes in the above, I registered listeners first then ran `instance.run()` to set things off (same principle as `server.listen()` pattern).

**Comment by patrickarlt** [comment]
> In the above I'm mixing callbacks and events. Not sure how I feel about doing that.

I'm mixing them in the top level `acetate` function and I don't like it. Especially since the callback fires multiple times (once each build).

> Note that events might fire before you register an event listener if you start the thing immediately on instantiation.

I run into this all the time on other projects. but I think its ok in this case. Most of this will be to simplify building things like the CLI and the Grunt tasks. The only event I'm planning to emit that users might not be able to listen to all of is `log` which probably isn't a big deal.

This is probably the case where you might miss some logs.

```js
var acetate = require('acetate');

var site = acetate(options);

// might miss some logs since `acetate` also invokes build(), ect...
site.on('log', handler);
```

But if your super paranoid about it you can pretty much do:

```
var Acetate = require('acetate/lib/acetate');

var site = new Acetate(options);

// won't miss anything
site.on('log', handler);

// do build/whatever yourself...
site.load(function(error){
  site.build(callback);
});
```

**Comment by ngoldman** [comment]
@patrickarlt I think that's reasonable as long as there's a way to deal with it internally that can be exposed. I'd say go event emitter all the way.

**Comment by patrickarlt** [comment]
This is now mostly switched to. I did have to add a `acetate.init()` thing. So now this looks like...

```js
var acetate = require('acetate');

var site = acetate(options);

// might miss some logs like starting build, error in config file, ect...
site.on('log', handler);
```

```js
var Acetate = require('acetate/lib/acetate');

var site = new Acetate();

// won't miss anything, including an error in your config file
site.on('log', handler);

// kick everything off...
acetate.init(options);

// do build/whatever yourself...
site.load(function(error){
  site.build(callback);
});
```
