### ISSUE TITLE
Underscores not ignored on folders

### ISSUE THREAD

**Issue by paulcpederson** [patrickarlt/acetate#46]
I have a folder full of markdown files. I don't want this parsed by acetate so I prefixed the folder name with `_` thinking this would keep the files from being built. 

All files still get built.

Is that the intended behavior?

**Comment by paulcpederson** [comment]
Another way to handle this would be to give me an 'ignore' helper in `acetate.conf.js` where I could pass a glob to the helper and it would ignore all those files.

**Comment by patrickarlt** [comment]
> Another way to handle this would be to give me an 'ignore' helper in acetate.conf.js

Try `ignore("folder/**/*")` in your `acetate.conf.js` :smile:

**Comment by paulcpederson** [comment]
http://acetate.io/documentation/ignoring-pages/ this might be a good place to document that. Leaving the issue open.

**Comment by patrickarlt** [comment]
@paulcpederson would you expect underscores on folders to ignore all pages? Or is the `ignore(somefolder/**/*)` helper enough?

**Comment by paulcpederson** [comment]
That's probably good enough.

**Comment by paulcpederson** [comment]
ok, I documented this, closing.
