### ISSUE TITLE
{{relativePath}} is incorrect for prettified urls

### ISSUE THREAD

**Issue by paulcpederson** [patrickarlt/acetate#47]
If I have a page in the root of my source folder called `sign-in.md` Acetate correctly builds that to `/sign-in/index.html`. This is great. 

The problem is that if I use `{{relativePath}}` for the layout of that page, it incorrectly calculates the path as if I am in the root folder, when in fact I know need to go up a level to be in the correct directory like `../`. 

This means that all js and css I load in named pages is broken and I am forced to make a folder called `sign-in` and create an `index.md` file in that folder which totally defeats the purpose of Acetate prettifying the url for me.

**Comment by nikolaswise** [comment]
@paulcpederson++

**Comment by paulcpederson** [comment]
this was fixed in v0.2.2
