### ISSUE TITLE
Generating JSON

### ISSUE THREAD

**Issue by nicholaswyoung** [patrickarlt/acetate#50]
Would it be possible to have a template (say ```src/posts.json```) that contained Nunjucks markup?

I would love the ability to create basic, read-only representations of content stored within the ```src/``` folder.

**Comment by patrickarlt** [comment]
@nicholaswyoung Yup i needs to be documented better but this should work.

```js
// acetate.conf.js
module.exports = function(acetate){
  acetate.source('posts.json'); // now posts.json will be parsed and processed with Nunjucls
}
```

A better alternative might be to write a simple custom extension (also needs more docs)

```js
// acetate.conf.js
module.exports = function(acetate){
  acetate.use(function(acetate, callback){
    // now you can read from acetate.pages build your json object and write it to the build folder
  });
}
```

**Comment by nicholaswyoung** [comment]
That's awesome. I'll give this a try, and if it works as expected, send a documentation patch.

**Comment by patrickarlt** [comment]
The next version of acetate will have an `output` helper you can use in your extensions or config file.

I'll get around to documenting it but you can reference the tests in the meanwhile. https://github.com/patrickarlt/acetate/blob/master/test/output-helper/acetate.conf.js
