### ISSUE TITLE
React?

### ISSUE THREAD

**Issue by nicholaswyoung** [patrickarlt/acetate#53]
I wonder how trivial it would be to add React templates to Acetate. That's how I'm building most UIs these days, and to integrate the templates into Acetate (with precompiled HTML rendering) would be the bomb. (I'll take a look at the template interface myself, but I'm posting this to gauge your interest in a PR.)

**Comment by patrickarlt** [comment]
@nicholaswyoung I would be interested in this but not as a part of Acetate core. this is probably fine as a separate extension.
