### ISSUE TITLE
Disable directory indexes for certain pages

### ISSUE THREAD

**Issue by paulcpederson** [patrickarlt/acetate#56]
Is there a way to disable pretty urls for certain pages/globs? Something like:

```
acetate.directoryIndex('templates/**/*', false);
```

If not, I could probably just ignore the files and then copy them, but wondering if this use case is addressed.

**Comment by paulcpederson** [comment]
Or even just in the frontmatter:

```
---
index: false
---
```

Or, perhaps via the metadata method:

```
acetate.metadata('this/page.html', {
  index: false
});
```

**Comment by patrickarlt** [comment]
The `prettyUrl` controls if the page will get an index.

So 

```
---
prettyUrl: false
---
```

or 

```
acetate.metadata('this/page.html', {
  prettyUrl: false
});
```

should both work.

**Comment by paulcpederson** [comment]
Yay!

**Comment by paulcpederson** [comment]
Documented this in acetate-site, https://github.com/patrickarlt/acetate-site/pull/13 and https://github.com/patrickarlt/acetate-site/pull/12
