### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by jf990** [patrickarlt/acetate#61]
A clean install of Acetate 1.0.0 from the repo following the npm instructions does not work. Both `__dirname` and `acetateRoot` are undefined.

```
/Users/john8301/Projects/acetate-map-view/node_modules/acetate-cli/bin/acetate.js:14
  var acetateCli = require(path.join(__dirname(acetateRoot), 'cli'));
                                     ^
TypeError: __dirname is not a function
    at /Users/john8301/Projects/acetate-map-view/node_modules/acetate-cli/bin/acetate.js:14:38
```

I was able to get my install to work by altering `acetate-cli/acetate.js` as follows
```
  var acetateRoot = pathToAcetate.replace(/(\/|\\)Acetate\.js/, '');
  var acetateCli = require(path.join(acetateRoot, 'cli'));
```

I was not able to figure out what the right definition for acetateRoot should have been, and could find no reference that would define it, so the hack I have seems to work. but obviously not the right answer.

**Comment by patrickarlt** [comment]
Should work now with `acetate-cli@1.0.1`.
